name: school
recipe: laravel

config:
  php: '7.4'
  composer_version: '2.0.7'
  via: apache:2.4
  webroot: public
  database: mysql:5.7
  cache: redis
  xdebug: false

services:
  node:
    type: node

tooling:
  npm:
    service: node
